import { NextResponse } from 'next/server'

// Curated daily thoughts for manifestation, presence, and living in desired energy
const DAILY_THOUGHTS = [
  "Today, feel into the energy of already having what you desire. Live from that state, not toward it.",
  "You don't manifest what you want—you manifest what you are. Embody the energy of your desired reality now.",
  "The fastest way to manifest is to stop waiting and start being. How would you feel if you already had it? Feel that now.",
  "Your thoughts create your reality, but your energy determines your experience. Align your energy with your desires.",
  "Manifestation isn't about getting—it's about becoming. Become the person who already has what you want.",
  "Live in the end state. Feel the gratitude, joy, and fulfillment of your desires as if they're already here.",
  "The universe responds to your energy, not your words. Embody the frequency of what you want to attract.",
  "Today, visualize your desired reality so vividly that your body feels it's already true. That's where manifestation begins.",
  "You are a magnet. What you focus on with feeling, you attract. Focus on the feeling of having, not wanting.",
  "Stop trying to manifest and start being the version of yourself who already has it. That's the secret.",
  "Your outer world reflects your inner state. Change your inner state, and watch your reality shift.",
  "Manifestation happens in the gap between where you are and where you want to be. Bridge it with feeling.",
  "Feel the energy of abundance, love, success—whatever you desire—right now. That feeling is the magnet.",
  "The present moment is where creation happens. Use it to feel into your desired reality, not to worry about how.",
  "You don't need to know how it will happen. You just need to know it's done. Feel that certainty now.",
  "Living in the end means feeling the completion of your desire in this moment. That's where the magic happens.",
  "Your vibration attracts your reality. Raise your vibration to match what you want to manifest.",
  "Today, act as if your desires are already fulfilled. Feel the gratitude, the joy, the peace of having them.",
  "Manifestation is not about waiting for the future—it's about creating it from the present moment with your energy.",
  "The energy you emit is what you receive. Emit the energy of your desired reality, and watch it materialize.",
  "Your desires are already yours. Feel the reality of having them, and watch them appear in your experience.",
  "The feeling of having is the bridge between where you are and where you want to be. Cross it now.",
  "Manifestation is an inside job. Change your inner world, and your outer world must follow.",
  "Feel the energy of your desired reality coursing through you. That's how you call it into being.",
  "You are the creator of your reality. Create from the feeling of already having what you want.",
  "The secret to manifestation: feel the end result so deeply that your current reality has no choice but to shift.",
  "Stop visualizing what you want. Start feeling what it's like to already have it. That's the key.",
  "Your future is created in the present moment through the energy you choose to embody right now.",
  "The universe doesn't care about your words—it responds to your vibration. Match the vibration of your desires.",
  "Living in the end means feeling complete, whole, and fulfilled about your desires in this very moment.",
  "You don't attract what you want—you attract what you are. Be the energy of your desires, and they will come.",
  "The fastest manifestation happens when you stop trying to get and start being the person who already has.",
  "Feel the gratitude of having your desires fulfilled. That feeling is the magnet that draws them to you.",
  "Your inner state creates your outer reality. Align your inner state with your desires, and watch them manifest.",
  "Manifestation is not about waiting—it's about becoming. Become the energy of what you want to attract.",
  "The feeling is the prayer. Feel the feeling of your desires being fulfilled, and the universe will respond.",
  "You are already everything you want to be. Feel that truth, and watch your reality reflect it back to you.",
  "The energy of your desired reality exists right now. Tune into it, embody it, and watch it materialize.",
  "Stop asking for what you want. Start feeling what it's like to already have it. That's manifestation.",
  "Your vibration is your invitation to the universe. Vibrate at the frequency of your desires, and they will arrive.",
  "The end state is not in the future—it's available to you right now through feeling. Feel it into existence.",
  "Manifestation is about alignment. Align your energy, thoughts, and feelings with your desires, and they must appear.",
  "Feel the joy, peace, and fulfillment of your desires as if they're already here. That feeling creates them.",
  "You are a powerful creator. Create your reality by feeling the energy of your desires in this moment.",
  "The bridge to your desires is feeling. Feel the feeling of having them, and you've already crossed the bridge.",
  "Your desires are already fulfilled in the quantum field. Feel that truth, and watch them appear in your reality.",
  "Manifestation happens when you stop focusing on lack and start feeling the energy of abundance.",
  "Feel into the version of yourself who already has everything you want. That's who you're becoming.",
  "The energy you embody is the reality you experience. Embody the energy of your desires, and they will manifest.",
  "Your inner world creates your outer world. Change your inner world to match your desires, and they will appear.",
  "Feel the certainty, the knowing, the absolute faith that your desires are already yours. That's the secret.",
  "Manifestation is not about getting—it's about receiving. Feel worthy, feel ready, feel that it's already done.",
  "The feeling of having is more powerful than the thought of wanting. Feel your desires into existence.",
  "You don't need to know how it will happen. You just need to feel that it's done. Feel that now.",
  "The energy of your desired reality is available to you right now. Access it through feeling, and watch it manifest.",
  "Feel the gratitude, the joy, the peace of having your desires fulfilled. That feeling is the creation point.",
  "Your vibration attracts your reality. Raise your vibration to match your desires, and they will come to you.",
  "Manifestation is about feeling the end result so deeply that your current reality shifts to match it.",
  "Feel the energy of abundance, success, love—whatever you desire—right now. That feeling is the magnet.",
  "You are the creator. Create your reality by feeling the energy of your desires in this present moment.",
  "The feeling is the prayer. Feel the feeling of your desires being fulfilled, and watch them materialize.",
  "Your inner state is the blueprint for your outer reality. Align your inner state with your desires.",
  "Feel the completion, the fulfillment, the satisfaction of having your desires. That feeling creates them.",
  "Manifestation happens when you stop trying to get and start being the energy of what you want.",
  "The energy of your desired reality exists in this moment. Feel it, embody it, and watch it appear.",
  "Feel the certainty that your desires are already yours. That certainty is what brings them into form.",
  "Your vibration is your reality. Vibrate at the frequency of your desires, and they will manifest.",
  "Feel the feeling of having your desires fulfilled. That feeling is the bridge to your desired reality.",
  "Manifestation is about feeling the end state so deeply that your current reality has no choice but to shift.",
  "You are already everything you want to be. Feel that truth, and watch your reality reflect it back.",
  "The feeling of having is the creation point. Feel your desires into existence right now.",
  "Your inner world creates your outer world. Change your inner world to match your desires.",
  "Feel the energy of your desired reality coursing through you. That's how you call it into being.",
  "Manifestation is not about waiting—it's about becoming. Become the energy of what you want to attract.",
  "The feeling is the prayer. Feel the feeling of your desires being fulfilled, and the universe will respond.",
  "You are a powerful creator. Create your reality by feeling the energy of your desires in this moment.",
  "Feel the gratitude of having your desires fulfilled. That feeling is the magnet that draws them to you.",
  "Your vibration attracts your reality. Raise your vibration to match your desires, and they will come.",
  "Feel the joy, peace, and fulfillment of your desires as if they're already here. That feeling creates them.",
  "Manifestation happens when you stop focusing on lack and start feeling the energy of abundance.",
  "Feel into the version of yourself who already has everything you want. That's who you're becoming.",
  "The energy you embody is the reality you experience. Embody the energy of your desires, and they will manifest.",
  "Your inner state creates your outer reality. Align your inner state with your desires, and watch them manifest.",
  "Feel the certainty, the knowing, the absolute faith that your desires are already yours. That's the secret.",
  "Manifestation is not about getting—it's about receiving. Feel worthy, feel ready, feel that it's already done.",
  "The feeling of having is more powerful than the thought of wanting. Feel your desires into existence.",
  "You don't need to know how it will happen. You just need to feel that it's done. Feel that now.",
  "The energy of your desired reality is available to you right now. Access it through feeling, and watch it manifest.",
  "Feel the gratitude, the joy, the peace of having your desires fulfilled. That feeling is the creation point.",
  "Your vibration attracts your reality. Raise your vibration to match your desires, and they will come to you.",
  "Manifestation is about feeling the end result so deeply that your current reality shifts to match it.",
  "Feel the energy of abundance, success, love—whatever you desire—right now. That feeling is the magnet.",
  "You are the creator. Create your reality by feeling the energy of your desires in this present moment.",
  "The feeling is the prayer. Feel the feeling of your desires being fulfilled, and watch them materialize.",
  "Your inner state is the blueprint for your outer reality. Align your inner state with your desires.",
  "Feel the completion, the fulfillment, the satisfaction of having your desires. That feeling creates them.",
  "Manifestation happens when you stop trying to get and start being the energy of what you want.",
  "The energy of your desired reality exists in this moment. Feel it, embody it, and watch it appear.",
  "Feel the certainty that your desires are already yours. That certainty is what brings them into form.",
  "Your vibration is your reality. Vibrate at the frequency of your desires, and they will manifest.",
  "Feel the feeling of having your desires fulfilled. That feeling is the bridge to your desired reality.",
  "Manifestation is about feeling the end state so deeply that your current reality has no choice but to shift.",
  "You are already everything you want to be. Feel that truth, and watch your reality reflect it back.",
  "The feeling of having is the creation point. Feel your desires into existence right now.",
  "Your inner world creates your outer world. Change your inner world to match your desires.",
  "Feel the energy of your desired reality coursing through you. That's how you call it into being.",
  "Manifestation is not about waiting—it's about becoming. Become the energy of what you want to attract.",
  "The feeling is the prayer. Feel the feeling of your desires being fulfilled, and the universe will respond.",
  "You are a powerful creator. Create your reality by feeling the energy of your desires in this moment.",
  "Feel the gratitude of having your desires fulfilled. That feeling is the magnet that draws them to you.",
  "Your vibration attracts your reality. Raise your vibration to match your desires, and they will come.",
  "Feel the joy, peace, and fulfillment of your desires as if they're already here. That feeling creates them.",
  "Manifestation happens when you stop focusing on lack and start feeling the energy of abundance.",
  "Feel into the version of yourself who already has everything you want. That's who you're becoming.",
  "The energy you embody is the reality you experience. Embody the energy of your desires, and they will manifest.",
  "Your inner state creates your outer reality. Align your inner state with your desires, and watch them manifest.",
  "Feel the certainty, the knowing, the absolute faith that your desires are already yours. That's the secret.",
  "Manifestation is not about getting—it's about receiving. Feel worthy, feel ready, feel that it's already done.",
  "The feeling of having is more powerful than the thought of wanting. Feel your desires into existence.",
  "You don't need to know how it will happen. You just need to feel that it's done. Feel that now.",
  "The energy of your desired reality is available to you right now. Access it through feeling, and watch it manifest.",
  "Feel the gratitude, the joy, the peace of having your desires fulfilled. That feeling is the creation point.",
  "Your vibration attracts your reality. Raise your vibration to match your desires, and they will come to you.",
  "Manifestation is about feeling the end result so deeply that your current reality shifts to match it.",
  "Feel the energy of abundance, success, love—whatever you desire—right now. That feeling is the magnet.",
  "You are the creator. Create your reality by feeling the energy of your desires in this present moment.",
  "The feeling is the prayer. Feel the feeling of your desires being fulfilled, and watch them materialize.",
  "Your inner state is the blueprint for your outer reality. Align your inner state with your desires.",
  "Feel the completion, the fulfillment, the satisfaction of having your desires. That feeling creates them.",
  "Manifestation happens when you stop trying to get and start being the energy of what you want.",
  "The energy of your desired reality exists in this moment. Feel it, embody it, and watch it appear.",
  "Feel the certainty that your desires are already yours. That certainty is what brings them into form.",
  "Your vibration is your reality. Vibrate at the frequency of your desires, and they will manifest.",
  "Feel the feeling of having your desires fulfilled. That feeling is the bridge to your desired reality.",
  "Manifestation is about feeling the end state so deeply that your current reality has no choice but to shift.",
  "You are already everything you want to be. Feel that truth, and watch your reality reflect it back.",
  "The feeling of having is the creation point. Feel your desires into existence right now.",
  "Your inner world creates your outer world. Change your inner world to match your desires.",
]

export async function GET() {
  try {
    // Get day of year (1-365/366) to ensure same thought each day
    const now = new Date()
    const start = new Date(now.getFullYear(), 0, 0)
    const diff = now.getTime() - start.getTime()
    const oneDay = 1000 * 60 * 60 * 24
    const dayOfYear = Math.floor(diff / oneDay)
    
    // Use day of year to select a thought (ensures same thought all day)
    const thoughtIndex = dayOfYear % DAILY_THOUGHTS.length
    const thought = DAILY_THOUGHTS[thoughtIndex]
    
    return NextResponse.json({ 
      thought,
      date: now.toISOString().split('T')[0], // YYYY-MM-DD format
      dayOfYear
    })
  } catch (error: any) {
    console.error('Error fetching daily thought:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to fetch daily thought' },
      { status: 500 }
    )
  }
}
