import { Artwork } from './types';

// Sample artwork data - replace with actual artwork images and details
export const artworkData: Artwork[] = [
  {
    id: '1',
    title: 'Vibrant Horizons',
    medium: 'Acrylic on Canvas',
    dimensions: '24" × 30"',
    year: 2024,
    category: 'painting',
    imageUrl: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80',
    description: 'An expressive exploration of color and form, capturing the dynamic energy of landscapes.',
    featured: true,
  },
  {
    id: '2',
    title: 'Urban Reflections',
    medium: 'Oil on Canvas',
    dimensions: '36" × 48"',
    year: 2024,
    category: 'painting',
    imageUrl: 'https://images.unsplash.com/photo-1578320338152-c68f52843e72?w=800&q=80',
    description: 'A contemporary take on cityscapes, blending abstraction with realism.',
    featured: true,
  },
  {
    id: '3',
    title: 'Floral Abstraction',
    medium: 'Mixed Media',
    dimensions: '20" × 24"',
    year: 2023,
    category: 'mixed-media',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80',
    description: 'Abstract representation of natural forms using various materials and techniques.',
    featured: true,
  },
  {
    id: '4',
    title: 'Contemplative Lines',
    medium: 'Charcoal and Graphite',
    dimensions: '18" × 24"',
    year: 2023,
    category: 'drawing',
    imageUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&q=80',
    description: 'A study in line and shadow, exploring the interplay of light and dark.',
  },
  {
    id: '5',
    title: 'Oceanic Dreams',
    medium: 'Acrylic on Canvas',
    dimensions: '30" × 40"',
    year: 2024,
    category: 'painting',
    imageUrl: 'https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800&q=80',
    description: 'Inspired by the ever-changing moods of the sea.',
    featured: true,
  },
  {
    id: '6',
    title: 'Geometric Harmony',
    medium: 'Mixed Media',
    dimensions: '22" × 28"',
    year: 2023,
    category: 'mixed-media',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80',
    description: 'Balancing structured forms with organic flow.',
  },
  {
    id: '7',
    title: 'Portrait Study',
    medium: 'Graphite on Paper',
    dimensions: '14" × 18"',
    year: 2023,
    category: 'drawing',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80',
    description: 'A detailed study capturing human emotion and expression.',
  },
  {
    id: '8',
    title: 'Sunset Symphony',
    medium: 'Oil on Canvas',
    dimensions: '28" × 36"',
    year: 2024,
    category: 'painting',
    imageUrl: 'https://images.unsplash.com/photo-1578320338152-c68f52843e72?w=800&q=80',
    description: 'Celebrating the dramatic colors of twilight.',
  },
  {
    id: '9',
    title: 'Abstract Flow',
    medium: 'Acrylic and Ink',
    dimensions: '24" × 30"',
    year: 2024,
    category: 'mixed-media',
    imageUrl: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80',
    description: 'Flowing forms and vibrant colors create a sense of movement and energy.',
  },
];

export const categories = [
  { id: 'all', label: 'All Work', value: 'all' as const },
  { id: 'painting', label: 'Paintings', value: 'painting' as const },
  { id: 'drawing', label: 'Drawings', value: 'drawing' as const },
  { id: 'mixed-media', label: 'Mixed Media', value: 'mixed-media' as const },
];

